spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_dev?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: recipe_dev_user
    password: some_password
  h2:
    console:
      enabled: false
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: error
    com.pablozoani.recipeapp: debug
    org.hibernate: info
    org.springframework: info

server:
  port: 8080