spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
logging:
  level:
    com:
      pablozoani:
        recipeapp: "debug"