spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_prod?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: recipe_prod_user
    password: some_password
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: validate
  devtools:
    add-properties: false

logging:
  level:
    root: error
    com.pablozoani.recipeapp: error
    org.hibernate: error
    org.springframework: error

server:
  port: 8080